name: Checkout Example
on: workflow_dispatch
jobs:
  checkout-repository:
	runs-on: ubuntu-20.04
	strategy:
  		matrix:
    			node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
